### ISSUE TITLE
Paginator overlaps with records-per-page

### ISSUE THREAD

**Issue by parijke** [laravel-filament/demo#77] opened 2023-08-20 09:54 UTC
![image](https://github.com/filamentphp/demo/assets/7671998/f848b30f-9bba-4da1-94c9-6b16dc5cbac8)

**Comment by Z3d0X** [comment] 2023-08-20 15:06
Bugs are to be reported on the main filament repo. Anyways this is a duplicate of https://github.com/filamentphp/filament/issues/7597

**Closed as not planned** 2023-08-20 17:19 UTC
