### ISSUE TITLE
Facing this issue on select component

### ISSUE THREAD

**Issue by HEMNATH1903** [laravel-filament/demo#101] opened 2024-04-29 05:21 UTC
Assume that we have another few more fields before this country field, and I am filling and moving from 1 field to another by 'Tab'. Once I landed in this field using 'Tab', I was trying to see the option using the Alt + down arrow. It is not working properly while accessing it through the keyboard. 

Are we missing anything here? I hope this is happening in the filament demo as well.

![image](https://github.com/filamentphp/demo/assets/35026250/fd70b972-a623-481e-9d88-b8d385b0b8db)

**Comment by zepfietje** [comment] 2024-06-08 10:16
Duplicate of https://github.com/filamentphp/filament/issues/5707.

**Closed as not planned by zepfietje** 2024-06-08 10:16 UTC
